api/urls.py
from django.urls import path
from .views import ProductoList, ProductoDetalle, ClienteList

urlpatterns = [
    path('v1/productos/',ProductoList.as_view(),name='producto_list'),
    path('v1/productos/<str:codigo>',ProductoDetalle.as_view(),name='producto_detalle'),
    path('v1/clientes/',ClienteList.as_view(),name='cliente_list')
]

app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include(('bases.urls', 'bases'), namespace='bases')),
    path('inv/', include(('inv.urls', 'inv'), namespace='inv')),
    path('cmp/', include(('cmp.urls', 'cmp'), namespace='cmp')),
    path('fac/', include(('fac.urls', 'fac'), namespace='fac')),
    path('api/', include(('api.urls', 'api'), namespace='api')),
    path('admin/', admin.site.urls),
]

bases/urls.py
from django.urls import path
from bases.views import Home, HomeSinPrivilegios
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('',Home.as_view(), name='home'),
    path('login/',auth_views.LoginView.as_view(template_name='bases/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='bases/login.html'), name='logout'),
    path('sin_privilegios/', HomeSinPrivilegios.as_view(), name='sin_privilegios'),
]

cmp/urls.py
from django.urls import path
from .reportes import imprimir_compra, reporte_compras
from .views import ProveedorView, ProveedorNew, ProveedorEdit, proveedorInactivar, \
    ComprasView, CompraDetDelete, compras

urlpatterns = [
    path('proveedores/',ProveedorView.as_view(), name="proveedor_list"),
    path('proveedores/new',ProveedorNew.as_view(), name="proveedor_new"),
    path('proveedores/edit/<int:pk>',ProveedorEdit.as_view(), name="proveedor_edit"),
    path('proveedores/inactivar/<int:id>',proveedorInactivar, name="proveedor_inactivar"),

    path('compras/',ComprasView.as_view(), name="compras_list"),
    path('compras/new',compras, name="compras_new"),
    path('compras/edit/<int:compra_id>',compras, name="compras_edit"),
    path('compras/<int:compra_id>/delete/<int:pk>',CompraDetDelete.as_view(), name="compras_del"),

    path('compras/listado', reporte_compras, name='compras_print_all'),
    path('compras/<int:compra_id>/imprimir', imprimir_compra,name="compras_print_one"),
]

fac/urls.py
from django.urls import path
from .reportes import imprimir_factura_recibo, imprimir_factura_list
from .views import ClienteEdit, ClienteNew, ClienteView, clienteInactivar, \
    FacturaView, facturas, ProductoView, borrar_detalle_factura

urlpatterns = [
    path('clientes/',ClienteView.as_view(), name="cliente_list"),
    path('clientes/new',ClienteNew.as_view(), name="cliente_new"),
    path('clientes/<int:pk>',ClienteEdit.as_view(), name="cliente_edit"),
    path('clientes/estado/<int:id>',clienteInactivar, name="cliente_inactivar"),

    path('facturas/',FacturaView.as_view(), name="factura_list"),
    path('facturas/new',facturas, name="factura_new"),
    path('facturas/edit/<int:id>',facturas, name="factura_edit"),
    path('facturas/buscar-producto',ProductoView.as_view(), name="factura_producto"),
    path('facturas/borrar-detalle/<int:id>',borrar_detalle_factura, name="factura_borrar_detalle"),
    path('facturas/imprimir/<int:id>',imprimir_factura_recibo, name="factura_imprimir_one"),
    path('facturas/imprimir-todas/<str:f1>/<str:f2>',imprimir_factura_list, name="factura_imprimir_all"),
]

inv/urls.py
from django.urls import path
from .views import CategoriaView, CategoriaNew, CategoriaEdit, CategoriaDel, \
    SubCategoriaView, SubCategoriaNew, SubCategoriaEdit, SubCategoriaDel, \
    MarcaView, MarcaNew, MarcaEdit, marca_inactivar, \
    UMView, UMNew, UMEdit, um_inactivar, \
    ProductoView, ProductoNew, ProductoEdit, producto_inactivar

urlpatterns = [
    path('categorias/', CategoriaView.as_view(), name='categoria_list'),
    path('categorias/new',CategoriaNew.as_view(), name='categoria_new'),
    path('categorias/edit/<int:pk>',CategoriaEdit.as_view(), name='categoria_edit'),
    path('categorias/delete/<int:pk>',CategoriaDel.as_view(), name='categoria_del'),

    path('subcategorias/',SubCategoriaView.as_view(), name='subcategoria_list'),
    path('subcategorias/new',SubCategoriaNew.as_view(), name='subcategoria_new'),
    path('subcategorias/edit/<int:pk>',SubCategoriaEdit.as_view(), name='subcategoria_edit'),
    path('subcategorias/delete/<int:pk>',SubCategoriaDel.as_view(), name='subcategoria_del'),

    path('marcas/',MarcaView.as_view(), name="marca_list"),
    path('marcas/new',MarcaNew.as_view(), name="marca_new"),
    path('marcas/edit/<int:pk>',MarcaEdit.as_view(), name="marca_edit"),
    path('marcas/inactivar/<int:id>',marca_inactivar, name="marca_inactivar"),

    path('um/',UMView.as_view(), name="um_list"),
    path('um/new',UMNew.as_view(), name="um_new"),
    path('um/edit/<int:pk>',UMEdit.as_view(), name="um_edit"),
    path('um/inactivar/<int:id>',um_inactivar, name="um_inactivar"),

    path('productos/',ProductoView.as_view(), name="producto_list"),
    path('productos/new',ProductoNew.as_view(), name="producto_new"),
    path('productos/edit/<int:pk>',ProductoEdit.as_view(), name="producto_edit"),
    path('productos/inactivar/<int:id>',producto_inactivar, name="producto_inactivar"),
]

templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>DarkNetSure</title>
    <!-- Custom fonts for this template-->
    <link
      href="{% static  'base/vendor/fontawesome-free/css/all.min.css' %}"
      rel="stylesheet"
      type="text/css"
    />
    <link
      href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
      rel="stylesheet"
    />
    <link href="{% static  'base/css/sb-admin-2.min.css' %}" rel="stylesheet" />
    <link
      href="{% static 'base/vendor/datatables/dataTables.bootstrap4.min.css'%}"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      href="{% static 'base/vendor/jquery_confirm/jquery-confirm.min.css' %}"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.min.css"
      integrity="sha256-DOS9W6NR+NFe1fUhEE0PGKY/fubbUCnOfTje2JMDw3Y="
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://unpkg.com/bootstrap-table@1.15.3/dist/bootstrap-table.min.css"
    />
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.8/css/select2.min.css"
      rel="stylesheet"
    />
  </head>
  <body id="page-top" class="bg-gradient-primary">
    {% block side_bar %}
    <!-- Page Wrapper -->
    <div id="wrapper">
      <!-- Sidebar -->
      <ul
        class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion"
        id="accordionSidebar"
      >
        <!-- Sidebar - Brand -->
        <a
          class="sidebar-brand d-flex align-items-center justify-content-center"
          href="{% url 'bases:home' %}"
        >
          <div class="sidebar-brand-icon rotate-n-15">
            <i class="fas fa-thumbs-up"></i>
          </div>
          <div class="sidebar-brand-text mx-3">DarkNetSure</div>
        </a>
        <hr class="sidebar-divider my-0" />
        <li class="nav-item">
          <a class="nav-link" href="{% url 'bases:home' %}">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Dashboard</span></a
          >
        </li>
        <hr class="sidebar-divider mt-0" />
        <div class="sidebar-heading">Opciones de Menú</div>
        <li class="nav-item">
          <a
            class="nav-link collapsed"
            href="#"
            data-toggle="collapse"
            data-target="#collapseOne"
            aria-expanded="true"
            aria-controls="collapseTwo"
          >
            <i class="fas fa-fw fa-book"></i>
            <span>Inventario</span>
          </a>
          <div
            id="collapseOne"
            class="collapse"
            aria-labelledby="headingTwo"
            data-parent="#accordionSidebar"
          >
            <div class="bg-white py-2 collapse-inner rounded">
              {% if perms.inv.view_categoria %}
              <a class="collapse-item" href="{% url 'inv:categoria_list' %}"
                >Categorías</a
              >
              {% endif %} {% if perms.inv.view_subcategoria %}
              <a class="collapse-item" href="{% url 'inv:subcategoria_list' %}"
                >Sub Categorias</a
              >
              {% endif %} {% if perms.inv.view_marca %}
              <a class="collapse-item" href="{% url 'inv:marca_list' %}"
                >Marcas</a
              >
              {% endif %} {% if perms.inv.view_unidadmedida %}
              <a class="collapse-item" href="{% url 'inv:um_list' %}"
                >Unidades de Medida</a
              >
              {% endif %} {% if perms.inv.view_producto %}
              <a class="collapse-item" href="{% url 'inv:producto_list' %}"
                >Productos</a
              >
              {% endif %}
            </div>
          </div>
        </li>
        <li class="nav-item">
          <a
            class="nav-link collapsed"
            href="#"
            data-toggle="collapse"
            data-target="#collapseTwo"
            aria-expanded="true"
            aria-controls="collapseTwo"
          >
            <i class="fas fa-fw fa-book"></i>
            <span>Catálogos</span>
          </a>
          <div
            id="collapseTwo"
            class="collapse"
            aria-labelledby="headingTwo"
            data-parent="#accordionSidebar"
          >
            <div class="bg-white py-2 collapse-inner rounded">
              {% if perms.cmp.view_proveedor %}
              <a class="collapse-item" href="{% url 'cmp:proveedor_list' %}"
                >Proveedores</a
              >
              {% endif %}
              {% if perms.cmp.view_cliente %}
              <a class="collapse-item" href="{% url 'fac:cliente_list' %}"
                >Clientes</a
              >
              {% endif %}
            </div>
          </div>
        </li>
        <li class="nav-item">
          <a
            class="nav-link collapsed"
            href="#"
            data-toggle="collapse"
            data-target="#collapseThree"
            aria-expanded="true"
            aria-controls="collapseTwo"
          >
            <i class="fas fa-fw fa-truck"></i>
            <span>Movimientos</span>
          </a>
          <div
            id="collapseThree"
            class="collapse"
            aria-labelledby="headingTwo"
            data-parent="#accordionSidebar"
          >
            <div class="bg-white py-2 collapse-inner rounded">
              {% if perms.cmp.view_compra %}
              <a class="collapse-item" href="{% url 'cmp:compras_list' %}"
                >Compras</a
              >
              {% endif %}

              {% if perms.cmp.view_factura %}
              <a class="collapse-item" href="{% url 'fac:factura_list' %}"
                >Facturas</a
              >
              {% endif %}
            </div>
          </div>
        </li>
        <hr class="sidebar-divider d-none d-md-block" />
        <div class="text-center d-none d-md-inline">
          <button class="rounded-circle border-0" id="sidebarToggle"></button>
        </div>
      </ul>
      <!-- End of Sidebar -->
      {% endblock side_bar %}

      <!-- Content Wrapper -->
      <div id="content-wrapper" class="d-flex flex-column">
        <!-- Main Content -->
        <div id="content">
          {% block top_bar %}
          <!-- Topbar -->
          <nav
            class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow"
          >
            <!-- Sidebar Toggle (Topbar) -->
            <button
              id="sidebarToggleTop"
              class="btn btn-link d-md-none rounded-circle mr-3"
            >
              <i class="fa fa-bars"></i>
            </button>

            <!-- Topbar Navbar -->
            <ul class="navbar-nav ml-auto">
              <div class="topbar-divider d-none d-sm-block"></div>

              <!-- Nav Item - User Information -->
              <li class="nav-item dropdown no-arrow">
                <a
                  class="nav-link dropdown-toggle"
                  href="#"
                  id="userDropdown"
                  role="button"
                  data-toggle="dropdown"
                  aria-haspopup="true"
                  aria-expanded="false"
                >
                  <span class="mr-2 d-none d-lg-inline text-gray-600 small"
                    >{{ user.username }}</span
                  >
                  <img
                    class="img-profile rounded-circle"
                    src="{% static 'base/img/user.png' %}"
                  />
                </a>
                <!-- Dropdown - User Information -->
                <div
                  class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                  aria-labelledby="userDropdown"
                >
                  <a
                    class="dropdown-item"
                    href="#"
                    data-toggle="modal"
                    data-target="#logoutModal"
                  >
                    <i
                      class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"
                    ></i>
                    Logout
                  </a>
                </div>
              </li>
            </ul>
          </nav>
          <!-- End of Topbar -->
          {% endblock top_bar %} {% block page_content %}
          <!-- Begin Page Content -->
          <div class="container-fluid">
            <!-- Page Heading -->
            <h1 class="h3 mb-4 text-gray-800">
              
            </h1>
          </div>
          {% endblock %}
          <!-- /.container-fluid -->
          {% block footer %}
        </div>
        <!-- End of Main Content -->

        <!-- Footer -->
        <footer class="sticky-footer bg-white">
          <div class="container my-auto">
            <div class="copyright text-center my-auto">
              <span>Copyright &copy; 2024</span>
            </div>
          </div>
        </footer>
        <!-- End of Footer -->
      </div>
      <!-- End of Content Wrapper -->
    </div>
    <!-- End of Page Wrapper -->
    {% endblock %} {% block login %} {% endblock %}
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
      <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div
      class="modal fade"
      id="logoutModal"
      tabindex="-1"
      role="dialog"
      aria-labelledby="exampleModalLabel"
      aria-hidden="true"
    >
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">¿Cerrar Sesión?</h5>
            <button
              class="close"
              type="button"
              data-dismiss="modal"
              aria-label="Close"
            >
              <span aria-hidden="true">×</span>
            </button>
          </div>
          <div class="modal-body">Desea cerrar sesión?.</div>
          <div class="modal-footer">
            <button
              class="btn btn-secondary"
              type="button"
              data-dismiss="modal"
            >
              Cancelar
            </button>
            <form method="post" action="{% url 'bases:logout' %}">
              {% csrf_token %}
              <button type="submit" class="btn btn-primary">Sí, Salir</button>
            </form>
          </div>
        </div>
      </div>
    </div>

    <div class="modal fade" id="popup"></div>

    <!-- Bootstrap core JavaScript-->
    <script src="{% static  'base/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static  'base/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static  'base/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static  'base/js/sb-admin-2.min.js' %}"></script>

    <!-- Page level plugins -->
    <script src="{% static 'base/vendor/datatables/jquery.dataTables.min.js'%}"></script>
    <script src="{% static 'base/vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>

    <script src="{% static 'base/vendor/jquery_confirm/jquery-confirm.min.js' %}"></script>

    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js"
      integrity="sha256-FEqEelWI3WouFOo2VWP/uJfs1y8KJ++FLh2Lbqc8SJk="
      crossorigin="anonymous"
    ></script>

    <script src="https://unpkg.com/bootstrap-table@1.15.3/dist/bootstrap-table.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.15.3/dist/bootstrap-table-locale-all.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.8/js/select2.min.js"></script>

    <script src="{% static  'base/js/jquery.chained.min.js' %}"></script>

    {% block control_modal%}
    <script>
      function abrir_modal(url) {
        $("#popup").load(url, function(){
          $(this).modal({
            backdrop:'static',
            keyboard: false
          })
          $(this).modal('show');
        });
        return false;
      }

      function cerrar_modal() {
        $('#popup').modal('hide');
        return false;
      }

      function mensaje(msg, color='green') {
        if (color=="success") { color="green"; }
        if (color=="error") { color="red"; }
        $.alert({
          title:'',
          theme:'material',
          type:color,
          content:msg
        });
      }

      {% if messages %}
        {% for message in messages %}
          console.log("{{ message.tags }}");
          mensaje("{{ message }}","{{ message.tags }}");
        {% endfor %}
      {% endif %}
    </script>
    {% endblock%} {% block js_page %} {% endblock %}
  </body>
</html>